#server:
#  port: 8081
#  #person:
#  #    birth: 2017/17/16
#  #    maps: {k1: v1,k2: v2}
#  #    lists:
#  #       - lisi
#  #       - zhangsan
#  #       - wangwu
#  #    dog:
#  #      name: 小狗
#  #      age: 12
#  #    age: 2
#  #    boss: true
##    last-name: zhangsan
#spring:
#  profiles:
#    active: dev
#---
#server:
#  port: 8082
#spring:
#  profiles: dev
#
#---
#server:
#  port: 8084
#spring:
#  profiles: prod